fix: worker threads not being recreated on exit
Gearlay/workerpool pull request #2
Opened 2023-11-30 14:03 UTC by maa105

## What's the issue this PR is solving?

Workers that exit are not replaced immidiately, add maxExec to options, add getNumberAvailableWorkers to pool, add typing

## What are you changing?

- add missing WorkerPoolOptions type
- add maxExec to options which only allows `maxExec` number of executions (if falsey will have no effect)
- in `_getWorker` remove terminated workers and only pick from "available" workers
- add `onWorkerExit` to WorkerHandler options which is called only once and when the worker exits and/or cannot accept new requests
- add `responseCount` to WorkerHandler to count number or responses and when they exceed `maxExec` will signal exit
- add `available()` to WorkerHandler which checks `requestCount` and `maxExec` along with busy/terminated/terminating/ready

### Notes

- This PR is needed by https://github.com/Gearlay/TokenStalker/pull/596
- since WorkerHandler was not linted I added a lint commit first then my work afterwards to make it easier to review and see what changed (check second commit)

### Types of changes

- New feature (non-breaking change which adds functionality)

## Screenshots / Screencasts

NA

2023-12-04 10:42 UTC, wbelhomsi reviewed
LGTM - ping abbas for a review on this too

2023-12-04 10:42 UTC, wbelhomsi commented on src/Pool.js
> +  const worker = new WorkerHandler(overridenParams.script || this.script, {
you can still return it from here

2023-12-04 11:10 UTC, maa105 commented on src/Pool.js
> +  const worker = new WorkerHandler(overridenParams.script || this.script, {
I need a reference to it to use in the onWorkerExit

2023-12-06 08:21 UTC, addo47 requested changes

2023-12-06 08:21 UTC, addo47 commented on src/Pool.js
> +    .forEach((worker) => this._removeWorker(worker));
Rather than iterating every time, I think it would be more optimal to simply check for termination after the selection process is done. If it's terminated, we remove and re-choose the worker. If it's not, all good.

2023-12-06 08:21 UTC, addo47 commented on src/WorkerHandler.js
> +    // console.log('exiting', Date.now());
Remove comment.

2023-12-06 08:21 UTC, addo47 commented on src/WorkerHandler.js
> +  var _onWorkerExit = options.onWorkerExit;
`let`

2023-12-06 08:21 UTC, addo47 commented on src/WorkerHandler.js
> +            me.terminating = true;
Would make more sense to set the flag prior to calling the handler.

2023-12-06 12:01 UTC, maa105 commented on src/Pool.js
> +    .forEach((worker) => this._removeWorker(worker));
We already do this in `onWorkerExit` this was put as an failsafe. I'll remove it. should be good

2023-12-06 12:15 UTC, maa105 commented on src/Pool.js
> +    .forEach((worker) => this._removeWorker(worker));
Removed

2023-12-06 12:16 UTC, maa105 commented on src/WorkerHandler.js
> +  var _onWorkerExit = options.onWorkerExit;
Done

2023-12-06 12:16 UTC, maa105 commented on src/WorkerHandler.js
> +    // console.log('exiting', Date.now());
Removed

2023-12-06 12:16 UTC, maa105 commented on src/WorkerHandler.js
> +            me.terminating = true;
Done

2023-12-06 21:00 UTC, addo47 approved these changes

2023-12-08 15:45 UTC, merged